name: Build, Test, Release, and Update docs

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'release tag version'
        default: 'X.Y.Z'
        required: true

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v2.3.2
      - name: git_config
        run: git config --local user.name "github_CI" && git config --local user.email "github_CI"
      - name: version_bump
      # when running this pipeline make sure the inputs.name is just the version without the v (eg: 1.1.1)
        run: sed -i '5s/.*/version = "${{ github.event.inputs.name }}"/' Cargo.toml
      - name: version_check
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: check
      - name: temp_branch
        continue-on-error: true
        run: git checkout -b tmp_branch
      - name: commit_and_push_new_docs
        continue-on-error: true
        run: git add Cargo.toml Cargo.lock && git commit -m "version bump ${{ github.event.inputs.name }}" && git push origin HEAD:tmp_branch
  build_test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.job.os }}
    needs: version_bump
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-18.04 , target: i686-unknown-linux-gnu , usecross: true }
          - { os: ubuntu-18.04 , target: x86_64-unknown-linux-gnu , usecross: false }
          - { os: windows-latest, target: x86_64-pc-windows-msvc, usecross: false }
          - { os: windows-latest, target: i686-pc-windows-msvc, usecross: false }
    steps:
      - name: install_rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
      - name: install_bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          # git bash does not have sudo, so if on windows, just do regular install
          # but if on linux you need sudo to install this
          if [[ -d /c/ ]]; then
              ./install.sh $HOME
          else
              sudo ./install.sh /usr/local
          fi
          # check if its installed
          bats --help
      - name: checkout_code
        uses: actions/checkout@v2.3.2
        with:
          ref: tmp_branch
      - name: test_gitfilter_1
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        working-directory: ./gitfilter
        with:
          use-cross: ${{ matrix.job.usecross }}
          command: build
          args: --release --examples --target=${{ matrix.job.target }}
      - name: test_gitfilter_2
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        working-directory: ./gitfilter
        with:
          use-cross: ${{ matrix.job.usecross }}
          command: test
          args: --target=${{ matrix.job.target }}
      - name: test_gitfilter_3
        working-directory: ./gitfilter
        run: bash -c "bats tests/gfr-simple.bats"
        env:
          GITFILTERCLI: ./target/${{ matrix.job.target }}/release/examples/gitfiltercli
      - name: test_gitfilter_4
        working-directory: ./gitfilter
        run: bash -c "bats tests/gfr-simple-two.bats"
        env:
          GITFILTERCLI: ./target/${{ matrix.job.target }}/release/examples/gitfiltercli
      - name: build_executable
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          use-cross: ${{ matrix.job.usecross }}
          command: build
          args: --release --target=${{ matrix.job.target }}
      - name: make_mgt_executable
        run: bash .github/make-mgt-executable.sh ${{ matrix.job.target }}

      # this works on linux but not windows for some reason...
      #       - name: echotest222
      #         run: echo ::set-env name=PROGRAM_PATH::$(realpath ./target/${{ matrix.job.target }}/release/mgt)

      # just a sanity check that it is executable...
      - name: program_help_test
        run: mgt -h
      - name: unit_test
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          use-cross: ${{ matrix.job.usecross }}
          command: test
          args: --target=${{ matrix.job.target }}
      - name: e2e_test_general
        run: bash -c "bats test/general"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_splitout
        run: bash -c "bats test/splitout"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_splitoutas
        run: bash -c "bats test/splitoutas"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_splitin
        run: bash -c "bats test/splitin"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_splitinas
        run: bash -c "bats test/splitinas"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_topbase
        run: bash -c "bats test/topbase"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_check
        run: bash -c "bats test/check"
        env:
          PROGRAM_PATH: mgt
      - name: e2e_test_sync
        run: bash -c "bats test/sync"
        env:
          PROGRAM_PATH: mgt
      - name: upload_artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: mgt-${{ matrix.job.target }}
          path: ./target/${{ matrix.job.target }}/release/
  release:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: download_all_artifacts
        uses: actions/download-artifact@v2.0.5
      - name: lstest
        run: ls -l
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.name }}
          release_name: v${{ github.event.inputs.name }}
          body: |
            TODO: fill this in
          draft: false
          prerelease: true
      - name: pack_asset_windows_64
        run: zip -j mgt-windows-64 ./mgt-x86_64-pc-windows-msvc/mgt.exe
      - name: upload_asset_windows_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./mgt-windows-64.zip
          asset_name: mgt-v${{ github.event.inputs.name }}-windows-64.zip
          asset_content_type: application/zip
      - name: pack_asset_windows_32
        run: zip -j mgt-windows-32 ./mgt-i686-pc-windows-msvc/mgt.exe
      - name: upload_asset_windows_32
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./mgt-windows-32.zip
          asset_name: mgt-v${{ github.event.inputs.name }}-windows-32.zip
          asset_content_type: application/zip
      - name: pack_asset_linux_64
        run: zip -j mgt-linux-64 ./mgt-x86_64-unknown-linux-gnu/mgt
      - name: upload_asset_linux_64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./mgt-linux-64.zip
          asset_name: mgt-v${{ github.event.inputs.name }}-linux-64.zip
          asset_content_type: application/zip
      - name: pack_asset_linux_32
        run: zip -j mgt-linux-32 ./mgt-i686-unknown-linux-gnu/mgt
      - name: upload_asset_linux_32
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./mgt-linux-32.zip
          asset_name: mgt-v${{ github.event.inputs.name }}-linux-32.zip
          asset_content_type: application/zip
  publish_docs:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: checkout_code
        uses: actions/checkout@v2.3.2
      - name: download_artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: mgt-x86_64-unknown-linux-gnu
          path: ./target/release
      - name: lstest
        run: ls -l ./target/release/mgt
      - name: merge_from_tmp
        run: git fetch origin tmp_branch && git checkout tmp_branch && git checkout - && git merge --ff-only tmp_branch
      - name: make_mgt_executable
        run: chmod +x ./target/release/mgt
      - name: helptest
        run: ./target/release/mgt --help
      - name: update_docs
        run: ./doc/gen_docs.sh
      - name: git_config
        run: git config --local user.name "github_CI" && git config --local user.email "github_CI"
      - name: commit_and_push_new_docs
        continue-on-error: true
        run: git add doc/ && git commit -m "updates docs for ${{ github.event.inputs.name }}" && git push
      - name: cleanup_tmp_branch
        run: git push origin --delete tmp_branch
        continue-on-error: true
